### ISSUE TITLE
Package requirements

### ISSUE THREAD

**Issue by bruth** [publicus/2018-06_shiny_example_biomedical_data#1]
When running the app in RStudio, I got an error stating that package `DT` needs to be installed. After installing it, the server started. Are there other packages and/or version that should be noted in the README?

**Comment by publicus** [comment]
Thank you for letting me know! I didn't see this until just now. The app does install dependencies automatically, but I missed declaring several across both the UI and Server files. (Alas, I didn't catch it when running it from a fresh version of the repo., as the packages were already installed on my system.) This has, I hope, been corrected in 1ea884f22 just now.

**Comment by publicus** [comment]
I have just now commented on #2 about having incorporated `packrat` for more fine-tuned package version control, as I hadn't realized that at least one tidyverse API I used is unstable.
