### ISSUE TITLE
Error on loading the "Explore" tab

### ISSUE THREAD

**Issue by bruth** [publicus/2018-06_shiny_example_biomedical_data#2]
Some of the chart loads, but under the "Resolved (Green) vs. Unresolved (Red) Cases, by Sex and Race" I get the following error. `Error: Evaluation error: no applicable method for 'replace_na' applied to an object of class "character".`

Full stack trace below. If it is relevant, I am running RStudio 1.0.153.

```
Warning: Error in mutate_impl: Evaluation error: no applicable method for 'replace_na' applied to an object of class "character".
Stack trace (innermost first):
    112: <Anonymous>
    111: stop
    110: mutate_impl
    109: mutate.tbl_df
    108: dplyr::mutate
    107: function_list[[k]]
    106: withVisible
    105: freduce
    104: _fseq
    103: eval
    102: eval
    101: withVisible
    100: %>%
     99: renderPlot [/Users/ruthb/tmp/2018-06_shiny_example_biomedical_data/1_application/server.R#325]
     89: <reactive:plotObj>
     78: plotObj
     77: origRenderFunc
     76: output$sankey_diagram
      1: runApp
Warning: Error in match: 'match' requires vector arguments
Stack trace (innermost first):
    105: %in%
    104: <Anonymous>
    103: FUN
    102: lapply
    101: map
    100: dots_capture
     99: dots_enquose
     98: quos
     97: filter.tbl_df
     96: dplyr::filter
     95: function_list[[k]]
     94: withVisible
     93: freduce
     92: _fseq
     91: eval
     90: eval
     89: withVisible
     88: %>%
     87: eval
     86: eval
     85: purrr::when
     84: function_list[[k]]
     83: withVisible
     82: freduce
     81: _fseq
     80: eval
     79: eval
     78: withVisible
     77: %>%
     76: filter_from_input [/Users/ruthb/tmp/2018-06_shiny_example_biomedical_data/1_application/server.R#126]
     75: function_list[[i]]
     74: freduce
     73: _fseq
     72: eval
     71: eval
     70: withVisible
     69: %>%
     68: <reactive:data_subset> [/Users/ruthb/tmp/2018-06_shiny_example_biomedical_data/1_application/server.R#139]
     57: r
     56: observerFunc
      1: runApp
Warning: Removed 4 rows containing missing values (geom_point).
```

**Comment by publicus** [comment]
Thank you for this! I will look today into whether this is a package version issue (perhaps with `tidyr`).

**Comment by publicus** [comment]
I was actually diagnosing a similar issue with another project today, and so found out two things:

1. There *does* seem to be a dependency issue with `tidyr`'s API having changed. 
1. `packrat` in R (for dependency management) does not work fully without restarting RStudio after an initial package install for a project (turning it off and on again *does* turn out to work in this case, after the initial package install, ha).

All this said, as of b0748eb, I have updated the repo. with new instructions and a few related file changes. I've also just now tested the updated instructions on a fresh machine running OSX with RStudio v. 1.0.153.
